### ISSUE TITLE
Simplify db interactions by using an ORM

### ISSUE THREAD

**Issue by PJColombo** [Blobscan/blobscan-indexer.rs#10]
We could use  [Diesel](https://github.com/diesel-rs/diesel)  for the PostgreSQL db

**Comment by 0xGabi** [comment]
Other alternative could be the prisma flavor: https://prisma.brendonovich.dev/getting-started/installation

**Comment by PJColombo** [comment]
We have decided to replace the use of ORMs with a standard REST API to separate the data storage layer from the data interaction layer.
