### ISSUE TITLE
Display more readable logs for local dev

### ISSUE THREAD

**Issue by PJColombo** [Blobscan/blobscan-indexer.rs#23]
Maybe we could use the [pretty formatter](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Pretty.html) for local dev and leave the json one for production?

**Comment by Evalir** [comment]
https://github.com/LukeMathWalker/bunyan can be used for this! no need to change the logs format depending on the environment. mb, should've pointed this out on the original recommendation/PR :)

**Comment by PJColombo** [comment]
Oh cool. Thanks for pointing it out
