### ISSUE TITLE
question: reorg about the blob transaction

### ISSUE THREAD

**Issue by shiziwen** [Blobscan/blobscan-indexer.rs#67]
Hi, I have a question about the blob transaction. We can get the blob data from the consensus node, such as by the rpc request: 

```
curl -X 'GET' \
  'http://localhost/eth/v1/beacon/blob_sidecars/0xfac836ec8196cd29bc95f3c7152117e5149b15784027f0af63b927bdef47432d' \
  -H 'accept: application/json' 
```

, does the blob transaction(type=0x3) will be reverted as normal transaction(type=0x2) ?

**Comment by PabloCastellano** [comment]
Hi @shiziwen. Could you elaborate more on what you are trying to achieve and how it is related with blobscan's indexer?
